### ISSUE TITLE
Disable Auto Refresh won't start

### ISSUE THREAD

**Issue by bexm1989** [OlapPivotTableExtensions/OlapPivotTableExtensions#10]
Hi everybody,

recentrly after years of use I started having issues.
Currently using version 0.9.0 on Excel 2016 Pro 64 bit
When I wan't to start "Disable Auto Refresh" I am getting a message
"First open Power Pivot window. If you continue to get this message, restart Excel and try again".

Ofcourse, I opened powerpivot and did everything right, but still stuck.
Also, I reinstalled the Olap as well as Office, but still the same.
Does anyone has an idea what could be the issue. 
Running of large workbooks, and every change in Powerpivot takes eternity now.
Please HELP !!

![issue olap](https://user-images.githubusercontent.com/41360895/42866732-b849d334-8a6d-11e8-98cf-08376cf9ace9.JPG)

**Comment by shawne004** [comment]
I am also having this issue....running the correct framework as well as the most current OPTE install..... and on Win7 x64...would love to use the disable feature again, soon......

**Comment by furmangg** [comment]
Thanks for reporting this. I'm now able to reproduce this behavior. I will keep the thread posted when I have a timeline for a fix.

**Comment by shawne004** [comment]
FYI - moved over to Win10 OS and still getting the same error.  Not sure if that helps or not, but wanted to let you know.

**Comment by XJSilver** [comment]
Hi, 

I have the same problem. 

![image](https://user-images.githubusercontent.com/34569124/45617188-cee53a00-ba71-11e8-803f-f6841e7ea164.png)

I use version 0.9.0 on Excel for Office 365 ProPlus MSO (16.0.10730.20102) 64-bit. Previous I could work around this error box by filtering a field in the pivot table in order to load the Data model and then clicking "Disable Auto Refresh" but this no longer works.

The workbook is unusable without the ability to "Disable Auto Refresh". I would really appreciate an update on the timeline for a fix. Thank you in advance.

**Comment by furmangg** [comment]
Thanks everyone for reporting this bug. It's on my list to look into this but I don't have a timeframe yet. I can reproduce the problem, though. It’s open source, so if you get to troubleshooting the code before me let me know. 

In case it helps, if you leave the PowerPivot window open and don’t change focus back to Excel or even to another window like Notepad, then Excel doesn’t recalculate. That was an Excel enhancement made since I wrote this feature.

Please do monitor this thread as I'll provide an update when this is fixed.

**Comment by asplinm** [comment]
shame pretty much the main feature I use. i also find even in Excel 2016 my pivots update even while I'm focused on the datamodel writing code. Really irritating.

**Comment by XJSilver** [comment]
My workbook is still unusable without the ability to "Disable Auto Refresh". I have resorted to installing an older version of Excel 2016. I would really appreciate an update on the timeline for a fix. Thank you in advance.

**Comment by furmangg** [comment]
Thank you all so much for your patience! I'm happy to announce that I've just posted the [0.9.5 release](https://github.com/OlapPivotTableExtensions/OlapPivotTableExtensions/releases) which fixes this issue. Please install the latest and let me know if you have troubles.

If you care about the details behind the scenes, thankfully it turned out to be a fairly small change to get it working again. Apparently PowerPivot (Excel Data Model) started loading into a separate AppDomain in Excel so my code which ensured it was loaded was only looking in the default AppDomain.
