### ISSUE TITLE
Installing Using SCCM

### ISSUE THREAD

**Issue by AndytheIT** [OlapPivotTableExtensions/OlapPivotTableExtensions#20]
Hi 
has anyone you know of managed to install the add-in using SCCM. 
We are using Excel 2016 64bit and it add the files to the local pc but does not register in Excel. If we  then double click on the Vsto file we get the following error
![image](https://user-images.githubusercontent.com/53005113/61375769-a3043200-a897-11e9-98b2-feaa2b69afa3.png)

**Comment by furmangg** [comment]
I don’t know much about SCCM but does this approach work?
https://sccmist.blogspot.com/2017/02/deploying-installshield-applications-in.html?m=1

**Comment by AndytheIT** [comment]
Hi I think this is to create an MSI?, I take it there isn’t an MSI version we could use?.
I think the problem is because the code is not signed as when you install manually you have to accept that it can’t identify the publisher

Andy

**Comment by furmangg** [comment]
If I read that article right it doesn’t require an MSI just an EXE. 

The DLL is signed. But I can’t recall if the installer is. It’s open source so if you figure out how to tweak the installer to make this work submit a pull request with the change or post back here.

**Comment by AndytheIT** [comment]
Hi,

No, those of our users that need it we install manually

Andy

**Comment by ty-james** [comment]
I know this issue is old however if you're deploying the OLAP extension via SCCM you need to also include a registry key located under the user's profile (HKCU\Software\Microsoft\Office\Excel\Addins) to get the extension to load properly

Key Name:
OlapPivotTableExtensions2016

Values:
[HKCU\Software\Microsoft\Office\Excel\Addins\OlapPivotTableExtensions2016]"Description"="String:An Excel add-in for SQL Server Analysis Services and Excel Data Models"

[HKCU\Software\Microsoft\Office\Excel\Addins\OlapPivotTableExtensions2016]"FriendlyName"="String:OLAP PivotTable Extensions"

[HKCU\Software\Microsoft\Office\Excel\Addins\OlapPivotTableExtensions2016]"LoadBehavior"="dword:00000003"

[HKCU\Software\Microsoft\Office\Excel\Addins\OlapPivotTableExtensions2016]"Manifest"="String:file:///C:\Program Files (x86)\OLAP PivotTable Extensions\OlapPivotTableExtensions.vsto|vstolocal"

![image](https://user-images.githubusercontent.com/66837704/86487505-86b50b80-bd1b-11ea-8fc5-af746d546c4e.png)


After adding this key and the listed values during your deployment the OLAP extension will load for the user.

**Comment by furmangg** [comment]
Thanks for sharing that part of the solution!

**Comment by AndytheIT** [comment]
Great thanks for the info

Andy
