### ISSUE TITLE
Registry entry for GUID

### ISSUE THREAD

**Issue by valemus** [OlapPivotTableExtensions/OlapPivotTableExtensions#22]
Dear developers,

I want to report a bug regarding the installation inside one of our organisations. The installation is not possible when a normal user is trying to install the extension having no admin rights, which is totally okay.

When an admin is doing the installation for the user in need of the extension, the GUID in the registry is set to the admin user. Therefore the normal user cannot use the extension because it is mapped to the admin that installed it for him.

Since this is a very urgent problem for us, we would like to request a fix in this matter and create the registry entries with the actual user GUID so that he is able to use the extension.

Thank you very much

Best regards,
Franjo

**Comment by valemus** [comment]
Hello,

since this is still a quite urgent problem, I wanted to ask if there is any update on this topic?

Best regards,
Franjo

**Comment by furmangg** [comment]
Thanks for reporting. I will plan to dig into this as part of the next release. I don’t have an immediate timeline on the next release and am super busy with my day job at the moment. 

If it’s urgent it is open source so feel free to fix the installer and share the fix with the community.

**Comment by Jmaxwell152** [comment]
Hello,

Due to the Caronavirus outbreak and increase in working from home, we have had to deploy some Windows Server 2019 Remote Desktop Services Servers.  The OLAP Pivottable Extensions program successfully installs however it only installs for the user you are currently logged on as.  

Having found this post, I presume that this is the reason why.  If so, are there any way to install this add-in for all users?  Even if there is a reg hack way of doing this for the time being?

Any quick solution would be appreciated to allow our users to work from home as quickly as possible.

Kin Regards,
Jamie

**Comment by BalyonR** [comment]
Hello!
Have a solution to our problem?

**Comment by furmangg** [comment]
This issue is fixed as part of [Release 0.9.6](https://github.com/OlapPivotTableExtensions/OlapPivotTableExtensions/releases/latest). It now installs OLAP PivotTable Extensions to the registry for all users, not just the user running setup.
