### ISSUE TITLE
Unable to cast COM object

### ISSUE THREAD

**Issue by powell-mitchell** [OlapPivotTableExtensions/OlapPivotTableExtensions#24]
![Capture](https://user-images.githubusercontent.com/61253697/74879971-4b034180-5338-11ea-967e-2bf4ad13c13c.PNG)

I have tried uninstalling and re-installing the add in a few times with no luck

**Comment by furmangg** [comment]
What version of Excel? Can you screenshot the About tab after opening OLAP PivotTable Extensions?

**Comment by powell-mitchell** [comment]
Excel 2013

![Capture](https://user-images.githubusercontent.com/61253697/74941936-e5f42e00-53c1-11ea-83c1-b8f4b4ff3449.PNG)

**Comment by furmangg** [comment]
I think this error is due to a mismatch with other Office software. What else is installed? Skype? Project? Version? 32-bit or 64?

https://github.com/OlapPivotTableExtensions/OlapPivotTableExtensions/issues/5

Also this article lends weight to that theory. 
https://docs.microsoft.com/en-us/archive/blogs/dau-blog/how-to-solve-unable-to-cast-com-object-of-type-microsoft-office-interop-excel-applicationclass-to-interface-type-microsoft-office-interop-excel-_application

**Comment by powell-mitchell** [comment]
I had downloaded MS Office 2016, but since then have deleted it.  I was under the impression that I had deleted all the keys for it as well.
